/**
 * File              : main.c
 * Author            : Igor V. Sementsov <ig.kuzm@gmail.com>
 * Date              : 01.04.2023
 * Last Modified Date: 09.05.2023
 * Last Modified By  : Igor V. Sementsov <ig.kuzm@gmail.com>
 */
/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "getbundle.h"

#include "prozubilib/prozubilib.h"

#include "patientList.h"
#include "configFile.h"

int
main (int argc, char *argv[])
{
  GtkWidget *mainWindow;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

	/*load files from bundle */
	
	//get bundle directory
	char *bundle = getbundle(argv);
	if (!bundle){
		g_error("can't get application bundle\n");
		return 1;
	}
	
	//crete directory in home dir
	char workdir[BUFSIZ];
	sprintf(workdir, "%s/%s", g_get_home_dir(), "gProZubi");
	g_mkdir_with_parents(workdir, 0755);
	
	//for MacOS set gtk_pixbuf paths
#ifdef __APPLE__
	char * loaders_cache = STR("%s/gdk-pixbuf-loaders.cache", workdir); 
	char * loaders_dir   = STR("%s/lib/gdk-pixbuf-2.0/2.10.0/loaders", bundle); 
	setenv("GDK_PIXBUF_MODULE_FILE", loaders_cache, true);
	setenv("GDK_PIXBUF_MODULEDIR",   loaders_dir,   true);
	setenv("GTK_PATH",        bundle, true);
	setenv("GTK_DATA_PREFIX", bundle, true);
	setenv("GTK_PATH",        bundle, true);
	//fix loaders cache
	fpstrrep(
			STR("%s/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache.in", bundle), 
			loaders_cache, 
			"$bundle", 
			bundle
			);
#endif

	//copy files from bundle
	char *files[] = 
	{
		"MKBCodes.sqlite", 
		"nomenklatura.sqlite", 
		NULL
	};
	for (int i = 0; files[i]; ++i) {
		GFile *sfile = g_file_new_build_filename(bundle,  files[i], NULL);
		GFile *dfile = g_file_new_build_filename(workdir, files[i], NULL);
		
		GError *error = NULL;
		g_file_copy(sfile, dfile, 0, NULL, NULL, NULL, &error);
		if (error)
			printf("g_file_copy error: %s\n", error->message);
	}

	//free bundle var
	free(bundle);

	//chworkdir
	chdir(workdir);	

	//get token
	char * token = token_from_config();
	g_print("init with token: %s\n", token);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  mainWindow = create_mainWindow ();
  widget_restore_state_from_config(mainWindow, "mainWindow", 640, 480); 
  GtkWidget *mainWindowLeftBox = lookup_widget(mainWindow, "mainWindowLeftBox");
  if (mainWindowLeftBox)
	widget_restore_state_from_config(mainWindowLeftBox, "mainWindowLeftBox", 300, 480); 

  /* init database */
  prozubi_t *p = prozubi_init(
		  "ProZubi.sqlite",
		  token);

  g_object_set_data(G_OBJECT(mainWindow), "prozubi", p);

  /* patient list as default at start */
  patient_list_new(mainWindow, p);

  gtk_widget_show (mainWindow);

  gtk_main ();
  return 0;
}

